UIF-442: Need new permission(s) to view Finance settings in UI
folio-org/ui-finance pull request #753
Opened 2023-08-23 10:51 UTC by alisher-epam

## Purpose

[UIF-442](https://issues.folio.org/browse/UIF-442) - add permissions and disable action buttons
## Approach

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-08-23 11:02 UTC, alisher-epam commented
The video source shows how it works. However, the example isn't complete due to don't have access to update permissions. It needs to be updated from thendatabase to check it locally.

2023-08-23 11:25 UTC, usavkov-epam commented
You also have to support i18n for new perms

2023-08-23 11:42 UTC, Terala-Priyanka requested changes

2023-08-23 11:42 UTC, Terala-Priyanka commented on package.json
> +        "displayName": "Settings (Finance): View settings",
Please add translations to the new permission name.

2023-08-23 11:42 UTC, Terala-Priyanka commented on package.json
> +        "displayName": "Settings (Finance): Export fund and expense class codes",
Please add translations to the new permission name.

2023-08-23 11:42 UTC, Terala-Priyanka commented on package.json
> +          "ui-finance.settings.view",
I think you can remove the below permissions in the list of sub-permissions when you add "ui-finance.settings.view" here, as they will be inherited.

"settings.finance.enabled",
          "finance.expense-classes.collection.get",
          "finance.fiscal-years.collection.get",
          "finance.fund-codes-expense-classes.collection.get",
          "finance.fund-types.collection.get",
          "users.collection.get"

2023-08-23 11:42 UTC, Terala-Priyanka commented on src/settings/FundTypeSettings/FundTypeSettings.js
> +        delete: () => !hasEditPerms,
you should frame the const hasEditPerms based on the specific PUT permission.
make another declaration for hasDeletePerms based on the specific DELET permission.
hook them accordingly to the actionSuppressor

2023-08-23 11:42 UTC, Terala-Priyanka commented on src/settings/ExpenseClassSettings/ExpenseClassSettings.js
> +        delete: () => !hasEditPerms,
you should frame the const hasEditPerms based on the specific PUT permission.
make another declaration for hasDeletePerms based on the specific DELET permission.
hook them accordingly to the actionSuppressor

2023-08-23 13:41 UTC, Terala-Priyanka approved these changes

2023-08-23 19:03 UTC, alisher-epam commented
[This PR](https://github.com/folio-org/ui-finance/pull/754) will resolve failing Github-actions https://github.com/folio-org/ui-finance/pull/754

2023-08-25 07:24 UTC, alisher-epam commented
@usavkov-epam please take a look at this PR when you have a chance please.

2023-08-25 12:37 UTC, mariia-aloshyna approved these changes

2023-08-25 12:37 UTC, mariia-aloshyna commented on src/settings/ExpenseClassSettings/ExpenseClassSettings.test.js
> +const stripesMock = { hasPerm: jest.fn(() => true) };
if you are not going to test `hasPerm` method then it should be just func - `() => true`, jest mock is not needed here

2023-08-25 14:28 UTC, merged